version: '3'

services:
  #  data:
  #    image: postgres:11.1-alpine
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      POSTGRES_DB: 'default'
  #      POSTGRES_USER: 'capstone2'
  #      POSTGRES_PASSWORD: 'capstone2'
  #    restart: always

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: demo_server_db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    links:
      - mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sourcecode
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      HOST_DB: mongodb
      NAME_DB: demo_server_db
    links:
      - mongodb
    entrypoint:
      - /entrypoint.sh
