# Generated by Django 3.0.9 on 2020-12-09 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200821_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 11, 37, 31, 837515)),
        ),
    ]
